In [1]:
!gdown --id 10wuVvdwBDYBhLqjB4KAucBTtRp0sfgkS
!gdown --id 1q6Uh03dxXg7IOwjhFJWvvY95oLf6btLC
!gdown --id 1dwiJA_mYQbxKhb3mS3_OIN2zq8kivc6m



# https://drive.google.com/file/d/1q6Uh03dxXg7IOwjhFJWvvY95oLf6btLC/view?usp=drive_link

/usr/local/lib/python3.10/dist-packages/gdown/cli.py:138: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=10wuVvdwBDYBhLqjB4KAucBTtRp0sfgkS
To: /content/model_GCN_CLOVE_TASK1.sav
100% 47.6k/47.6k [00:00<00:00, 75.2MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:138: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1q6Uh03dxXg7IOwjhFJWvvY95oLf6btLC
To: /content/word_to_ix.json
100% 166k/166k [00:00<00:00, 22.8MB/s]
/usr/local/lib/python3.10/dist-packages/gdown/cli.py:138: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From (original): 

In [2]:
!pip install torch_geometric

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 4.6 MB/s eta 0:00:00


In [3]:
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

class SimpleGCN(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super(SimpleGCN, self).__init__()
        self.conv1 = GCNConv(input_dim, 16)
        self.conv2 = GCNConv(16, output_dim)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = F.relu(self.conv1(x, edge_index))
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)

In [4]:
import pickle

# Load the model from the file
model_path = '/content/model_GCN_CLOVE_TASK1.sav'
with open(model_path,'rb') as f:
  model = pickle.load(f)

In [5]:
import json
import pandas as pd
import numpy as np

####change the path of the file here------------------------

test_file_path = '/content/test_file.json'

with open(test_file_path, 'r') as f:
    data_test = json.load(f)

In [6]:
for i in range(len(data_test)):
    for j in range(len(data_test[i]['speakers'])):
        data_test[i]['speakers'][j] = data_test[i]['speakers'][j].replace(" ", "_")


df_test = pd.DataFrame(data_test)



utterances_test = df_test['utterances'].tolist()
emotions_test = df_test['emotions'].tolist()
speakers_test = df_test['speakers'].tolist()
triggers_test = df_test['triggers'].tolist()

data_test = {
    'speakers': speakers_test,
    'emotions': emotions_test,
    'utterances': utterances_test,
    'triggers': triggers_test
}

df_test = pd.DataFrame(data_test)

In [7]:
all_speakers = "Stevens,The_Director,Paul,Cliff,Angela,Cookie,Paleontologist,Sophie,Teacher,Susan,Maitre_d',Another_Tour_Guide,Guy_#1,Mrs._Green,The_Hot_Girl,Mr._Posner,Joanne,Joey's_Hand_Twin,Dr._Miller,Monica,Stage_Director,Kiki,Singer,Another_Scientist,Sick_Bastard,Dr._Drake_Remoray,Chandler,Casey,Earl,Front_Desk_Clerk,Mrs._Geller,Chip,Kate,Mindy,Isabella,Joey_and_Chandler,Dana,Tom,Dr._Harad,Rick,Mr._Tribbiani,Hitchhiker,Bobby,Phoebe_Sr,1st_Customer,Man,Flight_Attendant,The_Guys,Kathy,Jeannine,The_Potential_Roommate,Waiter,Mona's_Date,Danny,Dr._Green,Tour_Guide,Gary,Ben,2nd_Customer,Director,Jen,Mrs._Tedlock,Issac,The_Grip,Dr._Leedbetter,TV_Announcer,Phoebe,Carl,Jane,Phoebe_and_Rachel,Bonnie,Frank,Barry,Mike,Janice,Guy,Friend_No._2,Stranger,Eric,Sarah,Nurse_#2,Phoebe_Sr.,PBS_Volunteer,Joey_and_Ross,The_Singing_Man,Jill,Charlton_Heston,Megan,Dr._Baldhara,Lorraine,Joey,Kim,Mr._Geller,Hold_Voice,Jay_Leno,Hotel_Clerk,Mr._Zelner,The_Conductor,Emeril,Tag,Gunther,Cassie,The_Food_Critic,Mrs._Lynch,Dr._Oberman,The_Casting_Director,Jade,Duncan,Woman_On_Train,Both,Elizabeth,Janine,Mr._Franklin,The_Interviewer,Dr._Stryker_Ramoray,Max,Krista,Older_Scientist,The_Museum_Official,Drunken_Gambler,Mr._Heckles,Ross_and_Rachel,Terry,Girl,Receptionist,Voice,Cecilia,Kyle,Young_Ethan,Richard,Dr._Wesley,Kristin,Policeman,Richard's_Date,Joey/Drake,Hoshi,Ursula,Leader,The_Smoking_Woman,Jester,Nurse_#1,Lauren,Larry,Steve,Trudie_Styler,Hope,Allesandro,Dr._Rhodes,an,Fireman_No._2,All,3rd_Customer,Aunt_Lillian,Nancy,Stanley,Dina,Fireman_No._3,Paolo,Ticket_Counter_Attendant,Monica_and_Phoebe,Jake,The_Librarian,Mona,Rachel,Gerston,Mark,Mischa,Boy_in_the_Cape,Russell,Doctor,Mr._Treeger,Fake_Monica,The_Cigarette_Guy,Carol,Alice,Doug,The_Security_Guard,Dr._Ledbetter,Mrs._Burgin,Rachel/actress,The_Lurker,Dr._Zane,The_Woman,Ronni,Kristen,Kori,David,The_Cooking_Teacher,Monica_and_Ross,Whitney,Monica_and_Rachel,Stage_Manager,Dr._Long,A_Female_Student,Leslie,Wayne,Nurse,Professore_Clerk,The_Vendor,Robert,Joanna,The_Dry_Cleaner,Joshua,Rachel_and_Phoebe,Message,Customer,Bernice,Supervisor,Lydia,Burt,The_Presenter,Bob,Annabelle,Petrie,Julio,Raymond,Estelle,Santos,Charlie,The_Acting_Teacher,Liam,Ms._McKenna,Katie,Woman,Chloe,Hombre_Man,A_Student,The_Instructor,Evil_Bitch,Peter,Pete,Paula,Emily,The_Fireman,Student,Tony,Julie,Fireman_No._1,Mrs._Chatracus,Jim,Mr._Burgin,Roger,The_Head_Librarian,Ross,Shelley"


all_speakers = all_speakers.split(",")

import json

# Specify the path to your JSON file
json_file_path = '/content/word_to_ix.json'

# Open and read the JSON file
with open(json_file_path, 'r') as file:
    # Load JSON data as a Python dictionary
    data = json.load(file)

# Now `data` is a Python dictionary containing the JSON content
word_to_ix=data


In [ ]:
print(all_speakers)

['Stevens', 'The_Director', 'Paul', 'Cliff', 'Angela', 'Cookie', 'Paleontologist', 'Sophie', 'Teacher', 'Susan', "Maitre_d'", 'Another_Tour_Guide', 'Guy_#1', 'Mrs._Green', 'The_Hot_Girl', 'Mr._Posner', 'Joanne', "Joey's_Hand_Twin", 'Dr._Miller', 'Monica', 'Stage_Director', 'Kiki', 'Singer', 'Another_Scientist', 'Sick_Bastard', 'Dr._Drake_Remoray', 'Chandler', 'Casey', 'Earl', 'Front_Desk_Clerk', 'Mrs._Geller', 'Chip', 'Kate', 'Mindy', 'Isabella', 'Joey_and_Chandler', 'Dana', 'Tom', 'Dr._Harad', 'Rick', 'Mr._Tribbiani', 'Hitchhiker', 'Bobby', 'Phoebe_Sr', '1st_Customer', 'Man', 'Flight_Attendant', 'The_Guys', 'Kathy', 'Jeannine', 'The_Potential_Roommate', 'Waiter', "Mona's_Date", 'Danny', 'Dr._Green', 'Tour_Guide', 'Gary', 'Ben', '2nd_Customer', 'Director', 'Jen', 'Mrs._Tedlock', 'Issac', 'The_Grip', 'Dr._Leedbetter', 'TV_Announcer', 'Phoebe', 'Carl', 'Jane', 'Phoebe_and_Rachel', 'Bonnie', 'Frank', 'Barry', 'Mike', 'Janice', 'Guy', 'Friend_No._2', 'Stranger', 'Eric', 'Sarah', 'Nurse_#2'

In [ ]:
print(word_to_ix)
print(all_speakers)

{'d-cup.': 0, 'catching': 1, 'canvas.': 2, 'beer.': 3, 'mistaken,': 4, 'hubba-bubba': 5, 'kidding': 6, 'bank': 7, 'line,': 8, 'vibe?': 9, '"it\'s': 10, "can't,": 11, 'course!': 12, 'sweating': 13, 'god!is': 14, 'home.': 15, 'clothes!': 16, 'r-r-richard': 17, 'pit': 18, 'hole,': 19, 'away,': 20, 'noise.': 21, 'countries': 22, 'lunch!': 23, 'granted': 24, 'number!': 25, 'starting': 26, 'feel?': 27, 'injure': 28, 'we\x92ll': 29, '7': 30, 'hulk.': 31, 'francis!': 32, 'roof': 33, 'docile.': 34, 'wedding...': 35, 'soon': 36, 'charm': 37, 'marriage?!': 38, 'queens,': 39, 'maybe!': 40, 'european': 41, 'dance.': 42, 'cinderelly.': 43, 'breaking?': 44, 'strangers.': 45, "victoria's": 46, 'sweetheart,': 47, 'crime': 48, 'sucks!': 49, 'thoughts': 50, 'ink': 51, 'side,': 52, 'duties?': 53, 'happened': 54, 'land': 55, 'jackass!': 56, 'then.': 57, 'bug,': 58, 'big,': 59, 'eyes,': 60, 'watch,': 61, 'finding': 62, 'him!': 63, 'see.': 64, 'nimitz,': 65, 'heads,': 66, 'bug': 67, 'philange.': 68, 'boobies

In [9]:
all_emotions=['sadness','neutral','joy','surprise','anger' ,'fear', 'disgust']
all_emotions=np.array(all_emotions)

In [10]:
from sklearn.preprocessing import OneHotEncoder
from torch_geometric.data import Data
import torch

emotion_encoder = OneHotEncoder()
speaker_encoder = OneHotEncoder()
all_speakers=np.array(all_speakers)
all_emotions=np.array(all_emotions)
speaker_encoder.fit(all_speakers.reshape(-1, 1))
emotion_encoder.fit(all_emotions.reshape(-1, 1))
def encode_features(row, glove_embeddings, word_to_ix, embedding_dim=200):
    # Encode speaker and emotion features
    speaker_features = speaker_encoder.transform(np.array(row['speakers']).reshape(-1, 1)).toarray()
    emotion_features = emotion_encoder.transform(np.array(row['emotions']).reshape(-1, 1)).toarray()

    # Encode text using GloVe
    text_features = np.zeros((len(row['utterances']), embedding_dim))
    for i, utterance in enumerate(row['utterances']):
        words = utterance.lower().split()
        word_vectors = np.array([glove_embeddings[word_to_ix[word]] for word in words if word in word_to_ix])
        if len(word_vectors) > 0:
            text_features[i] = np.mean(word_vectors, axis=0)  # Average the word vectors

    # Combine all features
    return np.concatenate([speaker_features, emotion_features, text_features], axis=1)


# Create edge indices
def create_edges(num_nodes):
    return np.array([[i, i+1] for i in range(num_nodes - 1)]).T


In [11]:
import numpy as np

def load_glove_embeddings(path, word_to_ix, embedding_dim=200):
    embeddings = np.zeros((len(word_to_ix), embedding_dim))
    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            values = line.split()
            word = values[0]
            if word in word_to_ix:
                vector = np.asarray(values[1:], dtype='float32')
                embeddings[word_to_ix[word]] = vector
    return embeddings

# Assuming word_to_ix is already defined as shown in previous examples
glove_path = '/content/glove.txt'  # Update with the path to your GloVe file
embedding_dim = 200  # Common dimensions are 50, 100, 200, 300
glove_embeddings = load_glove_embeddings(glove_path, word_to_ix, embedding_dim)

In [12]:

import torch.nn.functional as F
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
import numpy as np
from torch_geometric.data import Data

# Example modifications for evaluation and loss calculation
def evaluate(data):
    model.eval()
    with torch.no_grad():
        out = model(data)
    y_pred = F.log_softmax(out, dim=1)  # Convert to log-probabilities
    return y_pred

losses = []
accuracies = []
f1_scores = []
confusion_matrices = []
total_loss = 0
# emotion prediction dictionary
emotion_prediction = {}
n=0
# create a flip column to check if the emotion is in the list of emotions
for i in range(len(df_test)):
    emotion_dict={}
    features = encode_features(df_test.iloc[i], glove_embeddings, word_to_ix, 200)
    edge_index = create_edges(len(df_test.iloc[i]))
    tg_data = Data(x=torch.tensor(features, dtype=torch.float), edge_index=torch.tensor(edge_index, dtype=torch.long))
    tg_data.y = torch.tensor([np.argmax(line) for line in features[:, len(all_speakers):len(all_speakers)+len(all_emotions)]], dtype=torch.long)



    if tg_data.y.shape[0] <=3:
        continue
    n+=1
    y_pred = evaluate(tg_data)
    y_true = tg_data.y

    loss = F.nll_loss(y_pred, y_true)
    total_loss += loss.item()
    y_pred_labels = y_pred.argmax(dim=1)

    accuracies.append(accuracy_score(y_true, y_pred_labels))
    f1_scores.append(f1_score(y_true, y_pred_labels, average='macro'))
    for i in range(len(y_true)):
        # print the speaker id and emotion
        if y_true[i].item() in emotion_prediction:
            emotion_prediction[y_true[i].item()].append(y_pred_labels[i].item())
        else:
            emotion_prediction[y_true[i].item()] = [y_pred_labels[i].item()]
    confusion_matrices.append(confusion_matrix(y_true, y_pred_labels))
print(n)
print(f"Average Loss: {total_loss / n}")
print(f"Average Accuracy: {np.mean(accuracies)}")
print(f"Average F1 Score: {np.mean(f1_scores)}")
# print(f"Average Confusion Matrix:\n{np.mean(confusion_matrices, axis=0)}")
# for each emotion calculate the confusion matrix
# fincalConfusionMatrix = np.mean(confusion_matrices, axis=0)

# create final confusion matrix using the emotion_prediction dictionary
fincalConfusionMatrix = np.zeros((len(all_emotions), len(all_emotions)))
for key in emotion_prediction:
    for value in emotion_prediction[key]:
        fincalConfusionMatrix[key][value] += 1
# print(fincalConfusionMatrix)
# convert values to integers
fincalConfusionMatrix = fincalConfusionMatrix.astype(int)
print(fincalConfusionMatrix)



736
Average Loss: 0.6661264580249301
Average Accuracy: 0.7811308834853395
Average F1 Score: 0.7220083907615719
[[ 644    5    1   17  121   27   32]
 [   0  180    1    3   34    6    1]
 [   0    0  180    6   29    9    8]
 [   7    0    5  917  192    4   47]
 [  36    5   15  142 2691   35   85]
 [   6    0    1   11   74  401   18]
 [   4    3    2   41  142   21  758]]
